[build]
  command = "pnpm build"
  publish = "dist"

[dev]
  command = "pnpm dev"
  targetPort = 5137

[[redirects]]
  from = "/fund-memo"
  to = "https://pwv.notion.site/PWV-Fund-Memo-116b3e27e9b580cfb085e18e4281e407?pvs=4"
  status = 301
  force = true
  
[[redirects]]
  from = "/fundmemo"
  to = "https://pwv.notion.site/PWV-Fund-Memo-116b3e27e9b580cfb085e18e4281e407?pvs=4"
  status = 301
  force = true
