[build]
  command = "pnpm build"
  publish = "dist"

[dev]
  command = "pnpm dev"
  targetPort = 5137

[[redirects]]
  from = "/fund-memo"
  to = "https://fund.pwv.com/PWV-Fund-Memo-116b3e27e9b580cfb085e18e4281e407?pvs=4"
  status = 200
  
[[redirects]]
  from = "/fundmemo"
  to = "https://fund.pwv.com/PWV-Fund-Memo-116b3e27e9b580cfb085e18e4281e407?pvs=4"
  status = 200

[[redirects]]
  from = "/faq"
  to = "https://fund.pwv.com/FAQs-554dfb5b7d0f43db8a7a2724efc597f9?pvs=4"
  status = 200
